name: Notify on Markdown Change

on:
  push:
    paths:
      - '**/*.md'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to external endpoint
        run: |
          curl --location 'https://google.com'
